export type Decimal = string | number;
export type PosEmployee = { id: string; full_name: string; email: string | null; role: "admin" | "cashier"; active: boolean; created_at: string; has_open_session: boolean; has_orders: boolean };
export type RegisterState = {
  register_id: string;
  register_name: string;
  register_active: boolean;

  session_id: string | null;
  cashier_id: string | null;
  cashier_name: string | null;

  opened_at: string | null;
  opening_cash: Decimal | null;
  cash_payments: Decimal | null;
  cash_withdrawals: Decimal | null;
  cash_refunds: Decimal | null;
  expected_cash: Decimal | null;

  is_own: boolean;
  can_close: boolean;

  last_actual_closing_cash: Decimal | null;
  last_expected_closing_cash: Decimal | null;
  last_closed_at: string | null;
};export type RegisterReport = {
  registers: { id: string; name: string }[];
  cashiers: { id: string; full_name: string }[];
  sessions: (RegisterSession & { register_name: string; cashier_name: string; cash_payments: Decimal; cash_withdrawals: Decimal; cash_refunds: Decimal; expected_cash: Decimal | null })[];
};
export type CashWithdrawal = { id: string; request_id: string; request_fingerprint: string; session_id: string; register_id: string; actor_id: string; actor_name: string; register_name: string; amount: Decimal; reason: string; created_at: string };
type Stamp = { created_at: string; updated_at: string };
export type Customer = Stamp & { id: string; name: string; tax_code: string | null; phone: string | null; address: string | null; email: string | null; notes: string | null; active: boolean };
export type Register = Stamp & { id: string; name: string; active: boolean };
export type PaymentMethod = Stamp & { code: string; name: string; active: boolean; is_debt: boolean };
export type RegisterSession = { id: string; register_id: string; cashier_id: string; opened_at: string; opening_cash: Decimal; closed_at: string | null; expected_closing_cash: Decimal | null; actual_closing_cash: Decimal | null; cash_difference: Decimal | null; closing_note: string | null; status: "open" | "closed" };
export type CustomerPrice = Stamp & { id: string; customer_id: string; product_id: string | number | null; variant_id: string | number | null; price: Decimal };
export type Payment = { recorded_at: string; id: string; request_id: string; request_fingerprint: string | null; sale_id: string; session_id: string; received_by: string; method_code: string; method_name: string; kind: "sale_payment" | "repayment"; amount: Decimal; created_at: string };
export type Sale = { recorded_at: string; id: string; sale_number: number; request_id: string; request_fingerprint: string; cashier_id: string; cashier_name: string; session_id: string; sale_type: "retail" | "wholesale"; customer_id: string | null; customer_name: string | null; customer_tax_code: string | null; tracking_code: string | null; subtotal: Decimal; discount_total: Decimal; total: Decimal; paid_total: Decimal; debt_amount: Decimal; deferred_total: Decimal; deferred_method_name: string | null; status: "completed"; created_at: string };
export type SaleItem = { id: string; sale_id: string; line_number: number; target_kind: "product" | "variant"; product_id: string | number | null; variant_id: string | number | null; sku: string | null; product_name: string; variant_name: string | null; base_unit_price: Decimal; adjusted_unit_price: Decimal; quantity: Decimal; discount_percent: Decimal; final_unit_price: Decimal; line_total: Decimal; created_at: string };
export type CustomerTransaction = { id: string; customer_id: string; sale_id: string; payment_id: string | null; kind: "sale_charge" | "sale_payment" | "repayment" | "return_credit"; return_id: string | null; amount: Decimal; created_at: string };
export type PosReturn = { id: string; return_number: number; request_id: string; request_fingerprint: string; sale_id: string; session_id: string; actor_id: string; actor_name: string; reason: string; total_amount: Decimal; debt_reduction: Decimal; refund_total: Decimal; created_at: string };
export type PosReturnItem = { id: string; return_id: string; sale_item_id: string; quantity: Decimal; amount: Decimal; created_at: string };
export type PosReturnRefund = { id: string; return_id: string; session_id: string; method_code: string; method_name: string; amount: Decimal; created_at: string };
export type ReturnSaleDetails = {
  sale: { id: string; sale_number: number; sale_type: "retail" | "wholesale"; customer_name: string | null; total: Decimal; created_at: string };
  current_debt: Decimal;
  items: { id: string; line_number: number; sku: string | null; product_name: string; variant_name: string | null; quantity: Decimal; final_unit_price: Decimal; line_total: Decimal; returned_quantity: Decimal; returned_amount: Decimal }[];
} | null;
export type PosPurchase = { id: string; purchase_number: number; request_id: string; request_fingerprint: string; actor_id: string; actor_name: string; note: string | null; items_count: number; total: Decimal; created_at: string };
export type PosPurchaseItem = { id: string; purchase_id: string; line_number: number; target_kind: "product" | "variant"; product_id: string | null; variant_id: string | null; sku: string | null; product_name: string; variant_name: string | null; quantity: Decimal; unit_price: Decimal; previous_price: Decimal | null; line_total: Decimal };
export type PosInventory = { id: string; inventory_number: number; request_id: string; request_fingerprint: string; actor_id: string; actor_name: string; note: string | null; items_count: number; created_at: string };
export type PosInventoryItem = { id: string; inventory_id: string; line_number: number; target_kind: "product" | "variant"; product_id: string | null; variant_id: string | null; sku: string | null; product_name: string; variant_name: string | null; system_quantity: Decimal; counted_quantity: Decimal; difference: Decimal; reason: string };
export type PosStockMovement = { id: string; kind: "sale" | "return" | "purchase" | "inventory"; target_kind: "product" | "variant"; product_id: string | null; variant_id: string | null; sku: string | null; product_name: string; variant_name: string | null; quantity_change: Decimal; document_id: string; created_at: string };
export type InventoryCatalogItem = { kind: "product" | "variant"; id: string; name: string; sku: string | null; price: Decimal | null; stock: Decimal; cost: Decimal | null };
export type ProductOverviewItem = { kind: "product" | "variant"; id: string; name: string; variant_name: string | null; sku: string | null; price: Decimal | null; stock: Decimal; cost: Decimal | null; active: boolean };
type Table<Row> = { Row: Row; Insert: Partial<Row>; Update: Partial<Row>; Relationships: [] };
export type PosTables = {
  pos_cash_withdrawals: Table<CashWithdrawal>;
  pos_purchases: Table<PosPurchase>;
  pos_purchase_items: Table<PosPurchaseItem>;
  pos_inventories: Table<PosInventory>;
  pos_inventory_items: Table<PosInventoryItem>;
  pos_stock_movements: Table<PosStockMovement>;
  pos_returns: Table<PosReturn>;
  pos_return_items: Table<PosReturnItem>;
  pos_return_refunds: Table<PosReturnRefund>;
  pos_employee_audit: Table<{ id: string; actor_id: string; target_id: string; event: string; before_state: Json | null; after_state: Json | null; created_at: string }>;
  pos_business_customers: Table<Customer>;
  pos_registers: Table<Register>;
  pos_payment_methods: Table<PaymentMethod>;
  pos_customer_prices: Table<CustomerPrice>;
  pos_register_sessions: Table<RegisterSession>;
  pos_sales: Table<Sale>;
  pos_sale_items: Table<SaleItem>;
  pos_payments: Table<Payment>;
  pos_customer_transactions: Table<CustomerTransaction>;
};
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type SalesAnalytics = {
  item_mode: boolean;
  totals: {
    sales_count: number;
    quantity: number | string;
    gross: number | string;
    returns: number | string;
    net: number | string;
    cost: number | string;
    profit: number | string;
    unknown_cost_revenue: number | string;
  };
  weekdays: { day: number; sales_count: number; net: number | string }[];
  types: Partial<Record<"retail" | "wholesale", { sales_count: number; net: number | string }>>;
  top_products: { name: string; sku: string | null; quantity: number | string; net: number | string }[];
  received: number | string | null;
  debt: number | string | null;
};
export type AnalyticsProductRow = {
  name: string;
  sku: string | null;
  quantity: number | string;
  revenue: number | string;
  avg_price: number | string | null;
  unit_cost: number | string | null;
  cost: number | string | null;
  profit: number | string | null;
};
export type PosFunctions = {
  pos_products_overview: { Args: Record<string, never>; Returns: ProductOverviewItem[] };
  pos_create_product: { Args: { p_name: string; p_sku: string | null; p_price: string; p_cost: string | null; p_weight: string }; Returns: string };
  pos_set_cost: { Args: { p_kind: string; p_id: string; p_cost: string }; Returns: undefined };
  pos_update_product: { Args: { p_kind: string; p_id: string; p_price: string | null; p_active: boolean | null }; Returns: undefined };
  pos_inventory_catalog: { Args: Record<string, never>; Returns: InventoryCatalogItem[] };
  pos_create_purchase: { Args: { p_request: string; p_note: string | null; p_items: Json }; Returns: string };
  pos_create_inventory: { Args: { p_request: string; p_note: string | null; p_items: Json }; Returns: string };
  pos_complete_return: { Args: { p_request: string; p_session: string; p_sale: string; p_items: Json; p_refunds: Json; p_reason: string }; Returns: string };
  pos_sales_analytics: { Args: { p_from?: string | null; p_to?: string | null; p_type?: string | null; p_customer?: string | null; p_product?: string | null; p_sku?: string | null; p_min?: number | null; p_max?: number | null }; Returns: SalesAnalytics };
  pos_sales_analytics_products: { Args: { p_from?: string | null; p_to?: string | null; p_type?: string | null; p_customer?: string | null; p_product?: string | null; p_sku?: string | null; p_min?: number | null; p_max?: number | null }; Returns: AnalyticsProductRow[] };
  pos_return_sale_details: { Args: { p_number: number }; Returns: ReturnSaleDetails };
  pos_record_cash_withdrawal: { Args: { p_request: string; p_session: string; p_amount: string; p_reason: string }; Returns: string };
  pos_employee_list: { Args: Record<string, never>; Returns: PosEmployee[] };
  pos_employee_lookup: { Args: { p_email: string }; Returns: { id: string; has_pos: boolean } | null };
  pos_employee_save: { Args: { p_user: string; p_name: string; p_role: string; p_active: boolean }; Returns: string };
  pos_employee_password_request: { Args: { p_user: string; p_shared_confirm: boolean }; Returns: string };
  pos_employee_password_result: { Args: { p_request: string; p_success: boolean }; Returns: boolean };
  nexo_provisioning_version: { Args: Record<string, never>; Returns: number };
  pos_register_state: { Args: Record<string, never>; Returns: RegisterState[] };
  pos_register_session_report: { Args: { p_from?: string | null; p_to?: string | null; p_register?: string | null; p_cashier?: string | null; p_status?: string | null }; Returns: RegisterReport };
  pos_import_customer_prices: { Args: { p_customer: string; p_rows: Json }; Returns: number };
  pos_customer_balance: { Args: { p_customer: string }; Returns: number };
  pos_open_register: { Args: { p_register: string; p_cash: string }; Returns: string };
  pos_close_register: { Args: { p_session: string; p_actual: string; p_note?: string }; Returns: number };
  pos_quote: { Args: { p_kind: string; p_target: string; p_type: string; p_customer?: string }; Returns: Json };
  pos_set_customer_prices: { Args: { p_customer: string; p_rows: Json }; Returns: number };
  pos_complete_sale: { Args: { p_request: string; p_session: string; p_type: string; p_customer: string | null; p_tracking: string | null; p_items: Json; p_payments: Json; p_date?: string | null }; Returns: string };
  pos_record_repayment: { Args: { p_request: string; p_sale: string; p_session: string; p_method: string; p_amount: string; p_date?: string | null }; Returns: string };
};
