import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { before, after, test } from "node:test";
import { PGlite } from "@electric-sql/pglite";
import { membershipFor, provisionUser } from "../scripts/provision-user.mjs";

const db = new PGlite();
const query = async (sql, args=[]) => (await db.query(sql,args)).rows;
const sqlFile = async path => readFile(new URL(path,import.meta.url),"utf8");
const legacy = randomUUID();
let legacyBefore;
async function create(marker, userMetadata = {}, delayed = false) {
  const id=randomUUID();
  const app=marker === undefined ? {} : {nexo_memberships:marker};
  await query("insert into auth.users(id,email,raw_app_meta_data,raw_user_meta_data) values($1,'test@example.invalid',$2,$3)",
    [id,JSON.stringify(delayed ? {} : app),JSON.stringify(userMetadata)]);
  if (delayed) await query("update auth.users set raw_app_meta_data=$2 where id=$1",[id,JSON.stringify(app)]);
  return id;
}
async function asRole(role,id,sql,args=[]) {
  return db.transaction(async tx => {
    await tx.exec(`set local role ${role}`);
    await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[id ?? ""]);
    return (await tx.query(sql,args)).rows;
  });
}
const finalize = id => asRole("service_role",null,"select public.nexo_finalize_user_memberships($1) ok",[id]);
const rows = async id => ({orders:await query("select * from public.profiles where id=$1",[id]),pos:await query("select * from public.pos_profiles where id=$1",[id])});

before(async () => {
  await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
    create schema auth; create table auth.users(id uuid primary key,email text,raw_app_meta_data jsonb default '{}',raw_user_meta_data jsonb default '{}');
    create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
    grant usage on schema auth to authenticated;
    create table public.profiles(id uuid primary key references auth.users(id),full_name text,role text not null default 'operator' check(role in ('admin','operator','manager')),active boolean not null default true);
    create function public.handle_new_user() returns trigger language plpgsql security definer as $$ begin insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',new.email));return new;end $$;
    create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
    create function public.nexo_active_role() returns text language sql stable security definer set search_path='' as $$ select role from public.profiles where id=auth.uid() and active $$;
    create function public.is_admin() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.profiles where id=auth.uid() and active and role='admin') $$;
    create function public.is_active_user() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.profiles where id=auth.uid() and active) $$;
    alter table public.profiles enable row level security;
    create policy own_read on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
    create policy admin_update on public.profiles for update to authenticated using(public.is_admin()) with check(public.is_admin());
    grant select,update on public.profiles to authenticated;
    create table public.products(id bigint generated by default as identity primary key,name text,sku text,price numeric,weight_kg numeric,active boolean);
    create table public.product_variants(id bigint generated by default as identity primary key,product_id bigint references public.products(id),name text,sku text,price numeric,weight_kg numeric,active boolean);
    alter table public.products enable row level security; alter table public.product_variants enable row level security;
    grant select,insert,update,delete on public.products,public.product_variants to authenticated;
    grant usage on all sequences in schema public to authenticated;
    create policy products_read on public.products for select to authenticated using(public.is_active_user());
    create policy variants_read on public.product_variants for select to authenticated using(true);
    create policy products_admin on public.products for all to authenticated using(public.is_admin()) with check(public.is_admin());
    create policy variants_admin on public.product_variants for all to authenticated using(public.is_admin()) with check(public.is_admin());
    create policy products_write_restriction on public.products as restrictive for update to authenticated using(public.nexo_active_role() in ('admin','operator')) with check(public.nexo_active_role() in ('admin','operator'));
    insert into public.products(name,sku,price,active) values('Product','P1',10,true);
    insert into public.product_variants(product_id,name,sku,price,active) values(1,'Variant','V1',20,true);`);
  await query("insert into auth.users(id,email) values($1,'legacy@example.invalid')",[legacy]);
  await query("update profiles set role='admin',full_name='Existing administrator' where id=$1",[legacy]);
  await db.exec(await sqlFile("../supabase/migrations/202609260001_create_pos_profiles.sql"));
  await query("insert into pos_profiles(id,full_name,role,active) values($1,'Existing POS','cashier',false)",[legacy]);
  legacyBefore=await rows(legacy);
  await db.exec(await sqlFile("../supabase/prerequisites/202609280001_explicit_app_memberships.sql"));
  // Apply only in-memory, for integration of new membership with catalog reads.
  await db.exec(await sqlFile("../supabase/migrations/202609260002_pos_phase1.sql"));
  // Production Orders RPC source, exercised in the disposable fixture only.
  await db.exec(await sqlFile("./fixtures/orders-purchase-prices.sql"));
});
after(async()=>db.close());

test("unmarked Auth accounts no longer become Orders operators",async()=>{
  const id=await create();assert.deepEqual(await rows(id),{orders:[],pos:[]});
  assert.equal((await finalize(id))[0].ok,false);
});
test("POS admin and cashier receive POS membership only",async()=>{
  for(const role of ['admin','cashier']) {
    const id=await create({version:1,pos:role});const r=await rows(id);
    assert.equal(r.orders.length,0);assert.equal(r.pos[0].role,role);assert.equal(r.pos[0].active,true);
    assert.equal((await asRole('authenticated',id,'select public.nexo_active_role() role'))[0].role,null);
  }
});
test("Orders roles are provisioned only with explicit trusted markers",async()=>{
  for(const role of ['operator','admin','manager']) {
    const r=await rows(await create({version:1,orders:role},{full_name:'Employee'}));
    assert.equal(r.pos.length,0);assert.equal(r.orders[0].role,role);assert.equal(r.orders[0].active,true);assert.equal(r.orders[0].full_name,'Employee');
  }
});
test("migration leaves existing Orders and POS profiles byte-for-byte unchanged",async()=>{
  assert.deepEqual(await rows(legacy),legacyBefore);
});
test("invalid/unknown markers fail closed without partial memberships",async()=>{
  for(const marker of [null,'orders',[],{}, {version:2,orders:'admin'},{version:'1',orders:'admin'},
    {version:1,orders:'owner'}, {version:1,pos:'operator'}, {version:1,orders:'operator',pos:null},
    {version:1,orders:'operator',unexpected:true}]) {
    assert.deepEqual(await rows(await create(marker)),{orders:[],pos:[]});
  }
});
test("user-editable metadata cannot forge membership or roles",async()=>{
  const id=await create(undefined,{nexo_memberships:{version:1,orders:'admin',pos:'admin'},role:'admin'});
  assert.deepEqual(await rows(id),{orders:[],pos:[]});
  await assert.rejects(asRole('authenticated',id,"update auth.users set raw_app_meta_data='{}' where id=$1",[id]));
  await assert.rejects(asRole('authenticated',id,'select public.nexo_finalize_user_memberships($1)',[id]),/permission denied/);
  await assert.rejects(asRole('anon',null,'select public.nexo_provisioning_version()'),/permission denied/);
});
test("Admin API delayed metadata requires explicit completion, which is idempotent",async()=>{
  const id=await create({version:1,orders:'operator'}, {},true);
  assert.deepEqual(await rows(id),{orders:[],pos:[]});
  assert.equal((await finalize(id))[0].ok,true);const before=await rows(id);
  assert.equal((await finalize(id))[0].ok,true);assert.deepEqual(await rows(id),before);
});
test("dual access requires both explicit entries; later completion never overwrites profiles",async()=>{
  const id=await create({version:1,orders:'operator',pos:'cashier'});const r=await rows(id);
  assert.equal(r.orders.length,1);assert.equal(r.pos.length,1);
  const single=await create({version:1,pos:'cashier'});const before=await rows(single);
  await query("update auth.users set raw_app_meta_data=$2 where id=$1",[single,JSON.stringify({nexo_memberships:{version:1,pos:'cashier',orders:'operator'}})]);
  assert.equal((await rows(single)).orders.length,0);
  await finalize(single);assert.deepEqual((await rows(single)).pos,before.pos);
  await query("update auth.users set raw_app_meta_data=$2 where id=$1",[legacy,JSON.stringify({nexo_memberships:{version:1,orders:'operator'}})]);
  await assert.rejects(finalize(legacy),/EXISTING_ORDERS_MEMBERSHIP_CONFLICT/);
  assert.deepEqual(await rows(legacy),legacyBefore);
});
test("completion rolls back both grants when an existing membership conflicts",async()=>{
  const id=await create({version:1,pos:'cashier'});
  await query("update pos_profiles set active=false where id=$1",[id]);
  await query("update auth.users set raw_app_meta_data=$2 where id=$1",[id,JSON.stringify({nexo_memberships:{version:1,orders:'operator',pos:'cashier'}})]);
  await assert.rejects(finalize(id),/EXISTING_POS_MEMBERSHIP_CONFLICT/);
  const r=await rows(id);assert.equal(r.orders.length,0);assert.equal(r.pos[0].active,false);
});
test("POS-only roles read catalog but cannot INSERT UPDATE DELETE or use Orders catalog RPC",async()=>{
  for(const role of ['cashier','admin']) {
    const id=await create({version:1,pos:role});
    for(const table of ['products','product_variants']) {
      assert.equal((await asRole('authenticated',id,`select * from public.${table}`)).length,1);
      await assert.rejects(asRole('authenticated',id,`insert into public.${table}(name,price,active) values('Bad',1,true)`),/row-level security/);
      assert.equal((await asRole('authenticated',id,`update public.${table} set price=999 returning id`)).length,0);
      assert.equal((await asRole('authenticated',id,`delete from public.${table} returning id`)).length,0);
    }
    await assert.rejects(asRole('authenticated',id,"select public.nexo_create_catalog_item('product',$1,null)",[JSON.stringify({name:'Bad',price:1,weight_kg:1})]),/Only active admins/);
  }
});
test("existing Orders administrator still edits employees and manages catalog",async()=>{
  const employee=await create({version:1,orders:'operator'});
  assert.equal((await asRole('authenticated',legacy,"update profiles set full_name='Edited' where id=$1 returning id",[employee])).length,1);
  const result=await asRole('authenticated',legacy,"select public.nexo_create_catalog_item('product',$1,2) item",[JSON.stringify({name:'Admin product',price:10,weight_kg:1})]);
  assert.equal(result[0].item.name,'Admin product');
  assert.equal((await asRole('authenticated',legacy,"update products set price=11 where name='Admin product' returning id")).length,1);
  assert.equal((await asRole('authenticated',legacy,"delete from products where name='Admin product' returning id")).length,1);
});
test("privileged completion is service-only, with fixed search path and bypass owner",async()=>{
  const r=(await query("select p.prosecdef,p.proconfig,r.rolsuper,r.rolbypassrls,has_function_privilege('authenticated',p.oid,'EXECUTE') browser,has_function_privilege('service_role',p.oid,'EXECUTE') service from pg_proc p join pg_roles r on r.oid=p.proowner where p.oid='public.nexo_finalize_user_memberships(uuid)'::regprocedure"))[0];
  assert.equal(r.prosecdef,true);assert.ok(r.rolsuper||r.rolbypassrls);assert.equal(r.browser,false);assert.equal(r.service,true);assert.ok(r.proconfig.includes('search_path=""'));
});
test("provisioning command rejects implicit dual access and refuses legacy deployments",async()=>{
  assert.deepEqual(membershipFor({access:'pos'}),{version:1,pos:'cashier'});
  assert.throws(()=>membershipFor({access:'pos',ordersRole:'admin'}));
  assert.throws(()=>membershipFor({access:'unknown'}));
  let called=false;
  const client={rpc:async()=>({data:null,error:{}}),auth:{admin:{createUser:async()=>{called=true;}}}};
  await assert.rejects(provisionUser(client,{access:'orders',email:'x@example.invalid',fullName:'Test',password:'test-password-123'}),/prerequisite/);
  assert.equal(called,false);
});
test("trusted command supplies app metadata and completes membership after Auth creation",async()=>{
  const calls=[];let payload;
  const client={rpc:async(name)=>{calls.push(name);return {data:name==='nexo_provisioning_version'?1:true,error:null};},
    auth:{admin:{createUser:async(input)=>{calls.push('createUser');payload=input;return {data:{user:{id:legacy}},error:null};}}}};
  assert.equal(await provisionUser(client,{access:'dual',ordersRole:'operator',posRole:'admin',email:'x@example.invalid',fullName:'Test',password:'test-password-123'}),legacy);
  assert.deepEqual(calls,['nexo_provisioning_version','createUser','nexo_finalize_user_memberships']);
  assert.deepEqual(payload.app_metadata,{nexo_memberships:{version:1,orders:'operator',pos:'admin'}});
  assert.deepEqual(payload.user_metadata,{full_name:'Test'});assert.equal(payload.email_confirm,false);
});
